apiVersion: 1
datasources:
  - name: Google Cloud Monitoring
    type: stackdriver
    access: proxy
    isDefault: true
    jsonData:
      authenticationType: gce
      defaultProject: glowally-vllm