apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - monitoring.yaml

secretGenerator:
  - name: hf-token-secret
    envs:
      - secret.env
