apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # vLLM
  - deployment.yaml
  - service.yaml
  - monitoring.yaml
  # Grafana
  - grafana/deployment.yaml
  # KEDA: TODO: disable auto scaling/descaling for now as there is only 1 GPU qutoa.
  # Enable it once the GPU quota is increased.
  # - keda/scaled-object.yaml

secretGenerator:
  - name: hf-token-secret
    envs:
      - secret.env

generatorOptions:
  disableNameSuffixHash: true  # Keeps names predictable — no hash suffix added

configMapGenerator:
  - name: grafana-datasources
    files:
      - grafana/datasources.yaml
  - name: grafana-dashboard-providers
    files:
      - grafana/dashboard-provider.yaml
  - name: grafana-dashboards
    files:
      - grafana/dashboards/vllm.json